/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/yangguowei/Documents/我的个人博客/default/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-522e5e16",
    path: "/mac/command.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-522e5e16").then(next)
    },
  },
  {
    name: "v-01c55ff6",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01c55ff6").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6781f1a1",
    path: "/notes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6781f1a1").then(next)
    },
  },
  {
    path: "/notes/index.html",
    redirect: "/notes/"
  },
  {
    name: "v-7a345a8e",
    path: "/notes/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a345a8e").then(next)
    },
  },
  {
    path: "/notes/css/index.html",
    redirect: "/notes/css/"
  },
  {
    name: "v-327cff14",
    path: "/notes/css/compatibility.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-327cff14").then(next)
    },
  },
  {
    name: "v-b63f54cc",
    path: "/notes/css/layout.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b63f54cc").then(next)
    },
  },
  {
    name: "v-059000de",
    path: "/notes/css/commonUsed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-059000de").then(next)
    },
  },
  {
    name: "v-7d3b16d4",
    path: "/notes/git/git-range.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d3b16d4").then(next)
    },
  },
  {
    name: "v-31ff3056",
    path: "/notes/git/git-local.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31ff3056").then(next)
    },
  },
  {
    name: "v-450a5176",
    path: "/notes/git/git-ssh.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-450a5176").then(next)
    },
  },
  {
    name: "v-ac31fc14",
    path: "/notes/js/designMode/pattern.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ac31fc14").then(next)
    },
  },
  {
    name: "v-12c77454",
    path: "/notes/js/designMode/model.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12c77454").then(next)
    },
  },
  {
    name: "v-01ccbed6",
    path: "/notes/vue/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01ccbed6").then(next)
    },
  },
  {
    name: "v-45587bf6",
    path: "/notes/js/setmap.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45587bf6").then(next)
    },
  },
  {
    name: "v-2c3afe78",
    path: "/notes/others/contentType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c3afe78").then(next)
    },
  },
  {
    name: "v-4ca4bc48",
    path: "/notes/others/npm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ca4bc48").then(next)
    },
  },
  {
    name: "v-2ed6c15e",
    path: "/notes/wxapp/basics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ed6c15e").then(next)
    },
  },
  {
    name: "v-bc9e9c54",
    path: "/notes/wxapp/compatibility.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bc9e9c54").then(next)
    },
  },
  {
    name: "v-88ec4b24",
    path: "/notes/wxapp/scan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-88ec4b24").then(next)
    },
  },
  {
    name: "v-79680b56",
    path: "/notes/wxapp/scene.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79680b56").then(next)
    },
  },
  {
    name: "v-2ed91d5a",
    path: "/notes/wxapp/taroUsed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ed91d5a").then(next)
    },
  },
  {
    name: "v-5f03f5f6",
    path: "/notes/git/git-other.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f03f5f6").then(next)
    },
  },
  {
    name: "v-27eed8ab",
    path: "/questions/2019%E9%9F%A9%E5%AD%A6%E5%BC%BA%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27eed8ab").then(next)
    },
  },
  {
    path: "/questions/2019韩学强面试总结.html",
    redirect: "/questions/2019%E9%9F%A9%E5%AD%A6%E5%BC%BA%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html"
  },
  {
    path: "/questions/2019韩学强面试总结.html",
    redirect: "/questions/2019%E9%9F%A9%E5%AD%A6%E5%BC%BA%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html"
  },
  {
    name: "v-02344cc4",
    path: "/questions/2021%E5%B9%B41%E6%9C%88%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02344cc4").then(next)
    },
  },
  {
    path: "/questions/2021年1月面试总结.html",
    redirect: "/questions/2021%E5%B9%B41%E6%9C%88%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html"
  },
  {
    path: "/questions/2021年1月面试总结.html",
    redirect: "/questions/2021%E5%B9%B41%E6%9C%88%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html"
  },
  {
    name: "v-d8fbd62c",
    path: "/questions/2020%E5%B9%B412%E6%9C%88%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d8fbd62c").then(next)
    },
  },
  {
    path: "/questions/2020年12月面试总结.html",
    redirect: "/questions/2020%E5%B9%B412%E6%9C%88%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html"
  },
  {
    path: "/questions/2020年12月面试总结.html",
    redirect: "/questions/2020%E5%B9%B412%E6%9C%88%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html"
  },
  {
    name: "v-3d8805db",
    path: "/questions/docker%E9%9D%A2%E8%AF%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d8805db").then(next)
    },
  },
  {
    path: "/questions/docker面试.html",
    redirect: "/questions/docker%E9%9D%A2%E8%AF%95.html"
  },
  {
    path: "/questions/docker面试.html",
    redirect: "/questions/docker%E9%9D%A2%E8%AF%95.html"
  },
  {
    name: "v-6fbd8839",
    path: "/questions/2021%E5%B9%B44%E6%9C%88%E9%9F%A9%E5%AD%A6%E5%BC%BA%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fbd8839").then(next)
    },
  },
  {
    path: "/questions/2021年4月韩学强面试总结.html",
    redirect: "/questions/2021%E5%B9%B44%E6%9C%88%E9%9F%A9%E5%AD%A6%E5%BC%BA%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html"
  },
  {
    path: "/questions/2021年4月韩学强面试总结.html",
    redirect: "/questions/2021%E5%B9%B44%E6%9C%88%E9%9F%A9%E5%AD%A6%E5%BC%BA%E9%9D%A2%E8%AF%95%E6%80%BB%E7%BB%93.html"
  },
  {
    name: "v-3ea83d89",
    path: "/questions/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ea83d89").then(next)
    },
  },
  {
    path: "/questions/index.html",
    redirect: "/questions/"
  },
  {
    name: "v-3284d882",
    path: "/questions/webpack%E4%BC%98%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3284d882").then(next)
    },
  },
  {
    path: "/questions/webpack优化.html",
    redirect: "/questions/webpack%E4%BC%98%E5%8C%96.html"
  },
  {
    path: "/questions/webpack优化.html",
    redirect: "/questions/webpack%E4%BC%98%E5%8C%96.html"
  },
  {
    name: "v-66c6c496",
    path: "/questions/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66c6c496").then(next)
    },
  },
  {
    name: "v-5fa1304a",
    path: "/questions/%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E7%9B%B8%E5%85%B3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fa1304a").then(next)
    },
  },
  {
    path: "/questions/性能优化相关.html",
    redirect: "/questions/%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E7%9B%B8%E5%85%B3.html"
  },
  {
    path: "/questions/性能优化相关.html",
    redirect: "/questions/%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E7%9B%B8%E5%85%B3.html"
  },
  {
    name: "v-a658a400",
    path: "/questions/%E6%89%8B%E5%86%99Promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a658a400").then(next)
    },
  },
  {
    path: "/questions/手写Promise.html",
    redirect: "/questions/%E6%89%8B%E5%86%99Promise.html"
  },
  {
    path: "/questions/手写Promise.html",
    redirect: "/questions/%E6%89%8B%E5%86%99Promise.html"
  },
  {
    name: "v-54c02248",
    path: "/questions/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54c02248").then(next)
    },
  },
  {
    name: "v-6aec9260",
    path: "/questions/%E6%89%8B%E5%86%99Axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6aec9260").then(next)
    },
  },
  {
    path: "/questions/手写Axios.html",
    redirect: "/questions/%E6%89%8B%E5%86%99Axios.html"
  },
  {
    path: "/questions/手写Axios.html",
    redirect: "/questions/%E6%89%8B%E5%86%99Axios.html"
  },
  {
    name: "v-433ee636",
    path: "/questions/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-433ee636").then(next)
    },
  },
  {
    name: "v-a3ec6786",
    path: "/questions/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E9%9D%A2%E8%AF%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a3ec6786").then(next)
    },
  },
  {
    path: "/questions/小程序面试.html",
    redirect: "/questions/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E9%9D%A2%E8%AF%95.html"
  },
  {
    path: "/questions/小程序面试.html",
    redirect: "/questions/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E9%9D%A2%E8%AF%95.html"
  },
  {
    name: "v-84b8d2ea",
    path: "/questions/%E6%89%8B%E6%92%B8%E9%9D%A2%E8%AF%95%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-84b8d2ea").then(next)
    },
  },
  {
    path: "/questions/手撸面试题.html",
    redirect: "/questions/%E6%89%8B%E6%92%B8%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    path: "/questions/手撸面试题.html",
    redirect: "/questions/%E6%89%8B%E6%92%B8%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    name: "v-cbec05b2",
    path: "/questions/%E6%89%8B%E6%9C%BA%E7%AB%AF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cbec05b2").then(next)
    },
  },
  {
    path: "/questions/手机端.html",
    redirect: "/questions/%E6%89%8B%E6%9C%BA%E7%AB%AF.html"
  },
  {
    path: "/questions/手机端.html",
    redirect: "/questions/%E6%89%8B%E6%9C%BA%E7%AB%AF.html"
  },
  {
    name: "v-6efe9f82",
    path: "/questions/%E6%8E%92%E5%BA%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6efe9f82").then(next)
    },
  },
  {
    path: "/questions/排序.html",
    redirect: "/questions/%E6%8E%92%E5%BA%8F.html"
  },
  {
    path: "/questions/排序.html",
    redirect: "/questions/%E6%8E%92%E5%BA%8F.html"
  },
  {
    name: "v-171c5f5e",
    path: "/questions/%E8%BF%98%E5%9C%A8%E6%AD%BB%E8%AE%B0%E6%89%8B%E5%86%99%E9%9D%A2%E8%AF%95%E9%A2%98%E5%90%97.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-171c5f5e").then(next)
    },
  },
  {
    path: "/questions/还在死记手写面试题吗.html",
    redirect: "/questions/%E8%BF%98%E5%9C%A8%E6%AD%BB%E8%AE%B0%E6%89%8B%E5%86%99%E9%9D%A2%E8%AF%95%E9%A2%98%E5%90%97.html"
  },
  {
    path: "/questions/还在死记手写面试题吗.html",
    redirect: "/questions/%E8%BF%98%E5%9C%A8%E6%AD%BB%E8%AE%B0%E6%89%8B%E5%86%99%E9%9D%A2%E8%AF%95%E9%A2%98%E5%90%97.html"
  },
  {
    name: "v-53277b37",
    path: "/questions/%E6%89%8B%E5%86%99%E6%B7%B1%E6%8B%B7%E8%B4%9D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53277b37").then(next)
    },
  },
  {
    path: "/questions/手写深拷贝.html",
    redirect: "/questions/%E6%89%8B%E5%86%99%E6%B7%B1%E6%8B%B7%E8%B4%9D.html"
  },
  {
    path: "/questions/手写深拷贝.html",
    redirect: "/questions/%E6%89%8B%E5%86%99%E6%B7%B1%E6%8B%B7%E8%B4%9D.html"
  },
  {
    name: "v-0adbf2e0",
    path: "/questions/%E7%AE%97%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0adbf2e0").then(next)
    },
  },
  {
    path: "/questions/算法.html",
    redirect: "/questions/%E7%AE%97%E6%B3%95.html"
  },
  {
    path: "/questions/算法.html",
    redirect: "/questions/%E7%AE%97%E6%B3%95.html"
  },
  {
    name: "v-af51288e",
    path: "/service/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af51288e").then(next)
    },
  },
  {
    path: "/service/index.html",
    redirect: "/service/"
  },
  {
    name: "v-0bccb9b3",
    path: "/questions/%E9%9C%80%E8%A6%81%E7%9F%A5%E9%81%93%E7%9A%84%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0bccb9b3").then(next)
    },
  },
  {
    path: "/questions/需要知道的问题.html",
    redirect: "/questions/%E9%9C%80%E8%A6%81%E7%9F%A5%E9%81%93%E7%9A%84%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/questions/需要知道的问题.html",
    redirect: "/questions/%E9%9C%80%E8%A6%81%E7%9F%A5%E9%81%93%E7%9A%84%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-c035068c",
    path: "/questions/%E9%80%9F%E8%83%8C%E7%9F%A5%E8%AF%86%E7%82%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c035068c").then(next)
    },
  },
  {
    path: "/questions/速背知识点.html",
    redirect: "/questions/%E9%80%9F%E8%83%8C%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    path: "/questions/速背知识点.html",
    redirect: "/questions/%E9%80%9F%E8%83%8C%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    name: "v-83227f94",
    path: "/service/own.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-83227f94").then(next)
    },
  },
  {
    name: "v-395f12e2",
    path: "/tsNotes/ConditionalTypes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-395f12e2").then(next)
    },
  },
  {
    name: "v-75e9deb6",
    path: "/service/nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75e9deb6").then(next)
    },
  },
  {
    name: "v-55437cd6",
    path: "/tsNotes/IndexAccess.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55437cd6").then(next)
    },
  },
  {
    name: "v-239d6796",
    path: "/tsNotes/Keyof.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-239d6796").then(next)
    },
  },
  {
    name: "v-25865cba",
    path: "/tsNotes/Normal.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25865cba").then(next)
    },
  },
  {
    name: "v-6adcdef6",
    path: "/mac/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6adcdef6").then(next)
    },
  },
  {
    path: "/mac/index.html",
    redirect: "/mac/"
  },
  {
    name: "v-7ddc9ed0",
    path: "/tsNotes/Generics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ddc9ed0").then(next)
    },
  },
  {
    name: "v-5c7eb734",
    path: "/tsNotes/Typeof.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c7eb734").then(next)
    },
  },
  {
    name: "v-07b8ae9f",
    path: "/tsNotes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07b8ae9f").then(next)
    },
  },
  {
    path: "/tsNotes/index.html",
    redirect: "/tsNotes/"
  },
  {
    name: "v-547a7d54",
    path: "/tsNotes/ObjectType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-547a7d54").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]