/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/yangguowei/Documents/我的个人博客/我的笔记/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7c0e3121",
    path: "/notes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c0e3121").then(next)
    },
  },
  {
    path: "/notes/index.html",
    redirect: "/notes/"
  },
  {
    name: "v-5a9ce2d4",
    path: "/mac/command.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a9ce2d4").then(next)
    },
  },
  {
    name: "v-506ccf85",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-506ccf85").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-72299005",
    path: "/mac/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72299005").then(next)
    },
  },
  {
    path: "/mac/index.html",
    redirect: "/mac/"
  },
  {
    name: "v-f60adb8e",
    path: "/notes/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f60adb8e").then(next)
    },
  },
  {
    path: "/notes/css/index.html",
    redirect: "/notes/css/"
  },
  {
    name: "v-52d8115e",
    path: "/notes/css/commonUsed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52d8115e").then(next)
    },
  },
  {
    name: "v-16499e14",
    path: "/notes/css/compatibility.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16499e14").then(next)
    },
  },
  {
    name: "v-286e7c14",
    path: "/notes/git/git-ssh.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-286e7c14").then(next)
    },
  },
  {
    name: "v-afd3b314",
    path: "/notes/git/git-other.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-afd3b314").then(next)
    },
  },
  {
    name: "v-b0383fd4",
    path: "/notes/js/common.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b0383fd4").then(next)
    },
  },
  {
    name: "v-0a74a516",
    path: "/notes/git/git-range.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a74a516").then(next)
    },
  },
  {
    name: "v-1cfe33cc",
    path: "/notes/css/layout.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1cfe33cc").then(next)
    },
  },
  {
    name: "v-0769b656",
    path: "/notes/js/designMode/model.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0769b656").then(next)
    },
  },
  {
    name: "v-7b1160d6",
    path: "/notes/git/git-local.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b1160d6").then(next)
    },
  },
  {
    name: "v-70017bd4",
    path: "/notes/js/knowledge.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70017bd4").then(next)
    },
  },
  {
    name: "v-84ef9b14",
    path: "/notes/js/designMode/pattern.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-84ef9b14").then(next)
    },
  },
  {
    name: "v-ec39a714",
    path: "/notes/js/setmap.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ec39a714").then(next)
    },
  },
  {
    name: "v-1aaa8ef8",
    path: "/notes/others/contentType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1aaa8ef8").then(next)
    },
  },
  {
    name: "v-cd756670",
    path: "/notes/others/npm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd756670").then(next)
    },
  },
  {
    name: "v-1fbb11de",
    path: "/notes/wxapp/basics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fbb11de").then(next)
    },
  },
  {
    name: "v-9b03bb54",
    path: "/notes/wxapp/compatibility.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b03bb54").then(next)
    },
  },
  {
    name: "v-7c212dda",
    path: "/notes/wxapp/taroUsed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c212dda").then(next)
    },
  },
  {
    name: "v-20267bd6",
    path: "/notes/wxapp/scene.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20267bd6").then(next)
    },
  },
  {
    name: "v-c95c96d4",
    path: "/notes/react/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c95c96d4").then(next)
    },
  },
  {
    name: "v-3443af56",
    path: "/notes/vue/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3443af56").then(next)
    },
  },
  {
    name: "v-00bcfd09",
    path: "/questions/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00bcfd09").then(next)
    },
  },
  {
    path: "/questions/index.html",
    redirect: "/questions/"
  },
  {
    name: "v-4e6b3256",
    path: "/questions/compatible/Compatible.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e6b3256").then(next)
    },
  },
  {
    name: "v-3eb79140",
    path: "/questions/computer/ComputerNetWork.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3eb79140").then(next)
    },
  },
  {
    name: "v-92308494",
    path: "/questions/computer/SecurityNote.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-92308494").then(next)
    },
  },
  {
    name: "v-cdde5254",
    path: "/questions/dataStructure/Algorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cdde5254").then(next)
    },
  },
  {
    name: "v-a7789194",
    path: "/questions/dataStructure/Concept.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7789194").then(next)
    },
  },
  {
    name: "v-d471761c",
    path: "/questions/fontEndBasic/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d471761c").then(next)
    },
  },
  {
    name: "v-15df5fd6",
    path: "/questions/dataStructure/Sort.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15df5fd6").then(next)
    },
  },
  {
    name: "v-082a6aee",
    path: "/notes/wxapp/scan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-082a6aee").then(next)
    },
  },
  {
    name: "v-19325496",
    path: "/questions/autoTesting/AutoTesting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19325496").then(next)
    },
  },
  {
    name: "v-25048700",
    path: "/questions/fontEndBasic/CrossTerminal.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25048700").then(next)
    },
  },
  {
    name: "v-0a7a6104",
    path: "/questions/fontEndBasic/PerformanceOptimization.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a7a6104").then(next)
    },
  },
  {
    name: "v-5c766b0c",
    path: "/questions/fontEndBasic/React.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c766b0c").then(next)
    },
  },
  {
    name: "v-1c44f2b6",
    path: "/questions/fontEndBasic/JS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c44f2b6").then(next)
    },
  },
  {
    name: "v-72a660ec",
    path: "/questions/fontEndBasic/Vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72a660ec").then(next)
    },
  },
  {
    name: "v-65987414",
    path: "/questions/fontEndBasic/HTML.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65987414").then(next)
    },
  },
  {
    name: "v-ed638910",
    path: "/questions/fontEndBasic/WXApp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ed638910").then(next)
    },
  },
  {
    name: "v-9863d454",
    path: "/questions/questionHistory/2020.11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9863d454").then(next)
    },
  },
  {
    name: "v-ca774594",
    path: "/questions/questionHistory/2020.12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ca774594").then(next)
    },
  },
  {
    name: "v-82cb7814",
    path: "/questions/questionHistory/2021.04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82cb7814").then(next)
    },
  },
  {
    name: "v-a8d5a7c4",
    path: "/questions/fontEndBasic/Webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8d5a7c4").then(next)
    },
  },
  {
    name: "v-09b76dd6",
    path: "/questions/questionHistory/2021.01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09b76dd6").then(next)
    },
  },
  {
    name: "v-75059cb6",
    path: "/questions/written/Axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75059cb6").then(next)
    },
  },
  {
    name: "v-f6c83b54",
    path: "/questions/typescript/TypeScript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f6c83b54").then(next)
    },
  },
  {
    name: "v-684fc7b6",
    path: "/questions/questionHistory/2022.10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-684fc7b6").then(next)
    },
  },
  {
    name: "v-6bbccf96",
    path: "/questions/written/Promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bbccf96").then(next)
    },
  },
  {
    name: "v-42c84cee",
    path: "/questions/written/%E8%BF%98%E5%9C%A8%E6%AD%BB%E8%AE%B0%E6%89%8B%E5%86%99%E9%9D%A2%E8%AF%95%E9%A2%98%E5%90%97.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42c84cee").then(next)
    },
  },
  {
    path: "/questions/written/还在死记手写面试题吗.html",
    redirect: "/questions/written/%E8%BF%98%E5%9C%A8%E6%AD%BB%E8%AE%B0%E6%89%8B%E5%86%99%E9%9D%A2%E8%AF%95%E9%A2%98%E5%90%97.html"
  },
  {
    path: "/questions/written/还在死记手写面试题吗.html",
    redirect: "/questions/written/%E8%BF%98%E5%9C%A8%E6%AD%BB%E8%AE%B0%E6%89%8B%E5%86%99%E9%9D%A2%E8%AF%95%E9%A2%98%E5%90%97.html"
  },
  {
    name: "v-ad74f914",
    path: "/questions/written/ArrayObject.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad74f914").then(next)
    },
  },
  {
    name: "v-15b7eb39",
    path: "/service/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15b7eb39").then(next)
    },
  },
  {
    path: "/service/index.html",
    redirect: "/service/"
  },
  {
    name: "v-37489b20",
    path: "/questions/written/GetOutputResults.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37489b20").then(next)
    },
  },
  {
    name: "v-7d2d6e16",
    path: "/questions/written/Written.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d2d6e16").then(next)
    },
  },
  {
    name: "v-39d14954",
    path: "/regexp/regexp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39d14954").then(next)
    },
  },
  {
    name: "v-af3e6194",
    path: "/service/nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af3e6194").then(next)
    },
  },
  {
    name: "v-6b05a160",
    path: "/tsNotes/Generics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b05a160").then(next)
    },
  },
  {
    name: "v-c354a554",
    path: "/tsNotes/IndexAccess.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c354a554").then(next)
    },
  },
  {
    name: "v-27cea362",
    path: "/tsNotes/ConditionalTypes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27cea362").then(next)
    },
  },
  {
    name: "v-3ef1f0b6",
    path: "/service/own.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ef1f0b6").then(next)
    },
  },
  {
    name: "v-d3f9a58c",
    path: "/tsNotes/Normal.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d3f9a58c").then(next)
    },
  },
  {
    name: "v-deb9bf54",
    path: "/questions/questionHistory/2019.06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-deb9bf54").then(next)
    },
  },
  {
    name: "v-56145816",
    path: "/tsNotes/Keyof.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56145816").then(next)
    },
  },
  {
    name: "v-43888616",
    path: "/questions/written/DeepClone.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43888616").then(next)
    },
  },
  {
    name: "v-72b1dc54",
    path: "/tsNotes/ObjectType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72b1dc54").then(next)
    },
  },
  {
    name: "v-423d74e6",
    path: "/tsNotes/Typeof.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-423d74e6").then(next)
    },
  },
  {
    name: "v-75192e1f",
    path: "/tsNotes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75192e1f").then(next)
    },
  },
  {
    path: "/tsNotes/index.html",
    redirect: "/tsNotes/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]